# Generated by Django 2.1.7 on 2019-11-26 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('start_date', models.DateTimeField(verbose_name='Date et heure de début')),
                ('end_date', models.DateTimeField(verbose_name='Date et heure de fin')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Profile', verbose_name='Utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('localisation', models.CharField(max_length=200, verbose_name='Lieu')),
                ('capacity', models.IntegerField(default=10, verbose_name='Capacité')),
            ],
        ),
        migrations.CreateModel(
            name='RessourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
            ],
        ),
        migrations.AddField(
            model_name='ressource',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ressource.RessourceType'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='ressource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ressource.Ressource', verbose_name='Ressource'),
        ),
    ]
